package manipulator;



/*
 * Copyright (c) 2010, Oracle. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice,
 *   this list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Oracle nor the names of its contributors
 *   may be used to endorse or promote products derived from this software without
 *   specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */



import java.awt.Component;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class Manipulator extends javax.swing.JFrame {
    
    /** Creates new form Manipulator */
    public Manipulator() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbOpen = new javax.swing.JButton();
        tfStart = new javax.swing.JTextField();
        tfNumbers = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfUntil = new javax.swing.JTextField();
        jbFix = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Find");

        jbOpen.setText("Do it!");
        jbOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbOpenMouseClicked(evt);
            }
        });

        jLabel1.setText("Start");

        jLabel2.setText("Numbers");

        jLabel3.setText("Until");

        jbFix.setText("Fix it!");
        jbFix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbFixMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jbFix, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .add(jbOpen, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2)
                            .add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 17, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(tfUntil)
                            .add(tfNumbers)
                            .add(tfStart, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel1)
                    .add(tfStart, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tfNumbers, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tfUntil, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .add(8, 8, 8)
                .add(jbOpen)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbFix)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbOpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbOpenMouseClicked
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser(".");
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter ff = new FileNameExtensionFilter("SARP Replay (*.sre)", "sre");
        fc.setFileFilter(ff);
        int result = fc.showOpenDialog((Component)this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String src = fc.getSelectedFile().getAbsoluteFile().toString().toLowerCase();
            String des = src.replace(".sre", "_new.sre");
            
            XmlReader xr = new XmlReader(src);
            
            int nStart = Integer.parseInt(tfStart.getText());
            int nNumbers = Integer.parseInt(tfNumbers.getText());
            
            int cnt = xr.throughputSet.size();
            int index = xr.throughputSet.get(cnt-1).transaction;
            int until = Integer.parseInt(tfUntil.getText());
            float lastts[] = new float[nNumbers];
            ParentArraySet lastpr[] = new ParentArraySet[nNumbers];
            int i = 0;
            for(i = 0; i < nNumbers;i++){
                lastts[i] = xr.throughputSet.get(nStart + i).throughput;
                lastpr[i] = xr.parentSet.get(nStart + i);
            }
            
            int tmp = 0;
            for(cnt = 0; (index + cnt + 1) < until; cnt++){
                ThroughputArraySet tas = new ThroughputArraySet();
                tmp = cnt % nNumbers;
                tas.add(index + cnt + 1, lastts[tmp]);
                xr.throughputSet.add(tas);
                
                ParentArraySet pas = new ParentArraySet(index+cnt+1);
                
                for(i = 0; i < lastpr[tmp].size(); i++){
                    pas.add(lastpr[tmp].getSource(i), lastpr[tmp].getTarget(i));
                }
                xr.parentSet.add(pas);
            }
            
            XmlWriter xw = new XmlWriter(des);
            xw.saveThroughput(xr.throughputSet);
            xw.saveParent(xr.parentSet);
            xw.writeXml();
        }
    }//GEN-LAST:event_jbOpenMouseClicked

    private void jbFixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFixMouseClicked
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser(".");
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter ff = new FileNameExtensionFilter("SARP Replay (*.sre)", "sre");
        fc.setFileFilter(ff);
        int result = fc.showOpenDialog((Component)this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String src = fc.getSelectedFile().getAbsoluteFile().toString().toLowerCase();
            String des = src.replace(".sre", "_fix.sre");
            
            XmlReader xr = new XmlReader(src);
            
            int cnt = xr.throughputSet.size();
            int i = 0;
            
            for(i = 0; i < cnt; i++){
                xr.throughputSet.get(i).changeTransaction(xr.throughputSet.get(i).transaction - 1);
                xr.parentSet.get(i).changeTransaction(xr.parentSet.get(i).getTransaction() - 1);
            }
            
            XmlWriter xw = new XmlWriter(des);
            xw.saveThroughput(xr.throughputSet);
            xw.saveParent(xr.parentSet);
            xw.saveTrust(xr.trustSet);
            xw.writeXml();
        }
    }//GEN-LAST:event_jbFixMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manipulator().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbFix;
    private javax.swing.JButton jbOpen;
    private javax.swing.JTextField tfNumbers;
    private javax.swing.JTextField tfStart;
    private javax.swing.JTextField tfUntil;
    // End of variables declaration//GEN-END:variables
    
}
